#!/bin/bash -l        
#PBS -l walltime=3:00:00,nodes=1:ppn=16,mem=22gb 
#PBS -q lab
#PBS -o clean_journals.log
#PBS -m abe 
#PBS -M smit7982@umn.edu
#PBS -N CB_CLEAN_JOURNALS
module unload python
module load python2/2.7.12_anaconda4.1.1
source ~/venv/bin/activate
cd ~/text-analysis/scripts
rm -f /home/srivbane/shared/caringbridge/data/dev/clean_journals/all_keys.tsv
python ~/text-analysis/src/clean_journal/journals_manager.py --sites_dir /home/srivbane/shared/caringbridge/data/dev/parsed_json/ --keys_file /home/srivbane/shared/caringbridge/data/dev/clean_journals/all_keys.tsv --n_workers 16 --outfile /home/srivbane/shared/caringbridge/data/dev/clean_journals/1M_journals_for_topic.txt --log --clean_method topic
