#!/bin/bash -l        
#PBS -l walltime=5:00:00,nodes=1:ppn=24,mem=36gb 
#PBS -q small
#PBS -o clean_journals.log
#PBS -m abe 
#PBS -M smit7982@umn.edu
#PBS -N CB_CLEAN_JOURNALS
module unload python
module load python2/2.7.12_anaconda4.1.1
source ~/venv/bin/activate
cd ~/text-analysis/scripts
python ~/text-analysis/src/clean_journal/journals_manager.py --sites_dir /home/srivbane/shared/caringbridge/data/parsed_json/ --keys_file /home/srivbane/shared/caringbridge/data/clean_journals/all_keys.tsv --n_workers 24 --outfile /home/srivbane/shared/caringbridge/data/clean_journals/cleaned_journals.txt --log --clean_method topic
