#!/bin/bash -l        
#PBS -l walltime=0:05:00,nodes=1:ppn=16,mem=10gb 
#PBS -q lab
#PBS -o parse_journals.log
#PBS -m abe 
#PBS -M smit7982@umn.edu
#PBS -N CB_PARSE_JOURNALS
module unload python
module load python2/2.7.12_anaconda4.1.1
source ~/venv/bin/activate
cd ~/text-analysis/scripts
python ~/text-analysis/src/parse_journal/parse_manager.py --input_file /home/srivbane/shared/caringbridge/data/dev/journal.json --output_dir /home/srivbane/shared/caringbridge/data/dev/parsed_json/ --n_workers 16 --log --clean
