#!/bin/bash -l        
#PBS -l walltime=10:00:00,nodes=1:ppn=24,mem=36gb 
#PBS -q small
#PBS -o clean_journals.log
#PBS -m abe 
#PBS -M smit7982@umn.edu
#PBS -N CB_CLEAN_JOURNALS
module unload python
module load python2/2.7.12_anaconda4.1.1
source ~/venv/bin/activate
cd ~/text-analysis
rm -f /home/srivbane/shared/caringbridge/data/clean_journals/all_keys.tsv
python -m src.clean_journal.clean_manager --input_dir /home/srivbane/shared/caringbridge/data/parsed_json/  --output_file /home/srivbane/shared/caringbridge/data/clean_journals/clean_journals_for_topic.txt --clean_method topic --n_workers 24 --log
