#!/bin/bash -l        
#PBS -l walltime=3:00:00,nodes=1:ppn=16,mem=22gb 
#PBS -q lab
#PBS -o dev_clean_journals.log
#PBS -m abe 
#PBS -M smit7982@umn.edu
#PBS -N CB_DEV_CLEAN_JOURNALS
module unload python
module load python2/2.7.12_anaconda4.1.1
source ~/venv/bin/activate
cd ~/text-analysis
python -m src.clean_journal.clean_manager --input_dir /home/srivbane/shared/caringbridge/data/dev/parsed_json/ --outfile /home/srivbane/shared/caringbridge/data/dev/clean_journals/clean_journals_for_topic.txt --clean_method topic --n_workers 16 --log
