#!/bin/bash -l
#PBS -l walltime=1:00:00,nodes=1:ppn=16,mem=22gb
#PBS -q lab
#PBS -o dev_lda.log
#PBS -m abe
#PBS -M smit7982@umn.edu
#PBS -N DEV_LDA
module unload python
module load python2/2.7.12_anaconda4.1.1
source ~/venv/bin/activate
cd ~/text-analysis/scripts
DD=/home/srivbane/shared/caringbridge/data/dev/
fname=cleaned_journal1M_all.txt
python -m src.topic_model.gensim_lda --journal_file ${DD}clean_journals/${fname} --data_dir ${DD}topic_model --keep_n 10000 --num_test 1000 --num_docs 1000000 --num_topics 50 --chunksizes 256 --threshold 0.0 --n_workers 16 --evals_per_pass 10 --log --rebuild
