#!/bin/bash -l
#PBS -l walltime=12:00:00,nodes=1:ppn=1,mem=8gb
#PBS -q lab
#PBS -o matching_docs_to_topics.log
#PBS -m abe
#PBS -M smit7982@umn.edu
#PBS -N matching_docs_to_topics
module unload python
module load python2/2.7.12_anaconda4.1.1
source ~/venv/bin/activate
cd ~/text-analysis/scripts/logs
DD=/home/srivbane/shared/caringbridge/data/dev/topic_model/
python -m src.topic_model.extract_docs_matching_topics
