#!/bin/bash -l
#PBS -l walltime=12:00:00,nodes=1:ppn=1,mem=8gb
#PBS -q lab
#PBS -o extract_artifacts.log
#PBS -m abe
#PBS -M smit7982@umn.edu
#PBS -N extract_artifacts
module unload python
module load python2/2.7.12_anaconda4.1.1
source ~/venv/bin/activate
cd ~/text-analysis/scripts/logs
DD=/home/srivbane/shared/caringbridge/data/dev/
journal=cleaned_journal1M_all.txt
python -m src.topic_model.extract_model_artifacts --journal_file ${DD}clean_journals/${journal} --data_dir ${DD}topic_model --keep_n 10000 --num_test 1000 --num_docs 1000000 --num_topics 50 --n_workers 1 --log

